### ISSUE TITLE
asset store: getting 404 for Rakugo Template and Rakugo The Question

### ISSUE THREAD

**Issue by michael-conrad** [rakugoteam/VisualNovelKit#29]
**Describe the bug**
404 Errors

**To Reproduce**
Launch Godot
Try and download a Godot 3.2 template or demo

**Expected behavior**
Successful download

**Runtime (please complete the following information):**
 - Godot version: 3.2.4rc3
 - Rakugo Version: 2.1.02

**Comment by Jeremi360** [comment]
Please don't double the issue this is the same as #30 
I will fix it today.

**Comment by michael-conrad** [comment]
![image](https://user-images.githubusercontent.com/5229492/111011065-49068900-8366-11eb-90c4-100ef9d6099c.png)

**Comment by Jeremi360** [comment]
O I see now I misread this issue.
As I say it many times and this is also why you don't see any links to Godot's AssetLib, 
for now, I don't support AssetLib version because current AssetLib take very long to accept changes given in asset.
And I can't even delete this broken entries on their side.
If there will be a new version of AssetLib, then I will go back to support it.
And I know it will be around Godot 4.
But tomorrow I will try to give it a shot again and see if maybe there is a way to fix that.

**Comment by Jeremi360** [comment]
@michael-conrad I fixed them, but I don't know when changes will be accepted.
![obraz](https://user-images.githubusercontent.com/1294815/111024253-f23c9600-83dd-11eb-8c71-3ee0e8b94e43.png)
