### ISSUE TITLE
Html export to itch.io doesn't work

### ISSUE THREAD

**Issue by cmd16** [rakugoteam/VisualNovelKit#45]
**Describe the bug**
When uploading an html export from a project made with Rakugo, the game does not load correctly. When "Start" is clicked, the dialogue box just shows the default "some text" instead of the first dialogue. Desktop exports work fine.

**To Reproduce**
1. Create the default Rakugo project as described in [https://rakugodocs.readthedocs.io/en/latest/topics/project_setup/#create-rakugo-project](https://rakugodocs.readthedocs.io/en/latest/topics/project_setup/#create-rakugo-project)
2. Export to html
3. Upload the html build to itch.io
4. Run the game on itch.io
5. Click "Start"

**Expected behavior**
The first dialogue loads as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/23747622/114667827-f7874c00-9ccd-11eb-8a20-a509fe505e4a.png)

**Runtime (please complete the following information):**
 - Godot version [3.2.3.stable.official]
 - Rakugo Version [3.1.1]

**Comment by Jeremi360** [comment]
Now I see there is need a page about Export in Docs, I will add it soon.
**Edit I just add it:** https://rakugodocs.readthedocs.io/en/latest/topics/export/
@diman8 
First as there is mentioned in this paragraph:
https://rakugodocs.readthedocs.io/en/latest/topics/project_setup/#save-settings
Those Project Settings need to be changed before export:
- _rakugo/saves/test_mode_ -Set it to false before export.
- _rakugo/saves/save_folder_ - it is the path for the project’s saves folder. Before exporting, change it to start to _user://_ instead of _res://_

And from what I know project export settings need to be changed to:
- add `*.json` files
![image](https://user-images.githubusercontent.com/1294815/114683836-a6e51280-9d10-11eb-97a1-0b0a287b69b9.png)

- script export mode in the export settings from compiled to text
![image](https://user-images.githubusercontent.com/1294815/114680556-9bdcb300-9d0d-11eb-8b37-ab1f3a991cad.png)

This is standard for any Rakugo export, if it doesn't fix it then probably there some limitations to of Godot HTML export.
More about Godot exports here: https://docs.godotengine.org/en/3.0/getting_started/workflow/export/index.html

**Comment by cmd16** [comment]
I followed those instructions and am observing the same issue.

**Comment by Jeremi360** [comment]
@cmd16 Sorry I forgot, but Rakugo uses custom thread class for dialogs 
and from what I know, this doesn't work yet for Godot web version, so I can't fix it.
You need to wait for Godot version that will fix this,
 or I need to rewrote how I deal with dialogues, 
 but I don't have any idea for it now, and it will be a lot of work.

**Comment by Jeremi360** [comment]
@cmd16 New Godot version 3.3 should resolve this issue:
https://godotengine.org/article/godot-3-3-has-arrived#html5
I will update info docs soon.

**Comment by Jeremi360** [comment]
Docs are update to include what settings are need for HTML export.
https://rakugodocs.readthedocs.io/en/latest/topics/export/#for-html-export
